//! The Mode S check sequence.
//!
//! Every reply ends with 24 bits of parity over the rest of it, generated by
//! the polynomial the standard fixes (ICAO Annex 10 Volume IV, 3.1.2.3.3):
//!
//! ```text
//! x^24 + x^23 + x^22 + x^21 + x^20 + x^19 + x^18
//!      + x^17 + x^16 + x^15 + x^14 + x^13 + x^12 + x^10 + x^3 + 1
//! ```
//!
//! which is `0xFFF409` with the leading term implied.
//!
//! What makes this worth its own module is that the field is not always a plain
//! CRC. On a squitter or an all-call reply it is, and the syndrome of a good
//! message is zero. On an answer to an interrogation the aircraft's 24-bit
//! address is XORed into it, so the syndrome of a good message is *the
//! address* — the interrogator already knew who it had asked, and could
//! therefore recover the check by XORing that back. A receiver listening
//! passively did not ask, which is the whole reason [`crate::frame`] exists.

/// Generator polynomial, low 24 bits.
const POLY: u32 = 0x00FF_F409;

/// One byte's worth of the division, precomputed.
const TABLE: [u32; 256] = {
    let mut t = [0u32; 256];
    let mut i = 0;
    while i < 256 {
        let mut c = (i as u32) << 16;
        let mut k = 0;
        while k < 8 {
            c = if c & 0x0080_0000 != 0 { (c << 1) ^ POLY } else { c << 1 };
            k += 1;
        }
        t[i] = c & 0x00FF_FFFF;
        i += 1;
    }
    t
};

/// The syndrome of a message: the remainder over everything but the last three
/// bytes, XORed with the parity field they hold.
///
/// Zero for an intact squitter or all-call reply; the aircraft's address for an
/// intact surveillance or Comm-B reply; anything at all for a corrupted one.
pub fn syndrome(msg: &[u8]) -> u32 {
    if msg.len() < 4 {
        return u32::MAX;
    }
    let n = msg.len();
    let mut rem: u32 = 0;
    for &b in &msg[..n - 3] {
        rem = ((rem << 8) ^ TABLE[((rem >> 16) as u8 ^ b) as usize]) & 0x00FF_FFFF;
    }
    let parity = u32::from(msg[n - 3]) << 16 | u32::from(msg[n - 2]) << 8 | u32::from(msg[n - 1]);
    rem ^ parity
}

/// Write the parity for `msg` in place, as a transmitter would, optionally with
/// `overlay` (an address) XORed into it.
///
/// Here rather than in a test module because both the tests and the example
/// signal generator need it, and a generator that computes the check
/// differently from the decoder would prove nothing.
pub fn seal(msg: &mut [u8], overlay: u32) {
    let n = msg.len();
    if n < 4 {
        return;
    }
    msg[n - 3] = 0;
    msg[n - 2] = 0;
    msg[n - 1] = 0;
    let v = syndrome(msg) ^ overlay;
    msg[n - 3] = (v >> 16) as u8;
    msg[n - 2] = (v >> 8) as u8;
    msg[n - 1] = v as u8;
}

#[cfg(test)]
mod tests {
    use super::*;

    fn hex(s: &str) -> Vec<u8> {
        (0..s.len() / 2).map(|i| u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).unwrap()).collect()
    }

    /// Published extended squitters check out to zero. This is the whole
    /// decoder's foundation: if the polynomial or the bit order were wrong,
    /// every frame on the band would be rejected and the panel would simply be
    /// empty.
    #[test]
    fn a_published_squitter_has_a_zero_syndrome() {
        for m in [
            "8D40621D58C382D690C8AC2863A7",
            "8D40621D58C386435CC412692AD6",
            "8D4840D6202CC371C32CE0576098",
            "8DA3D42599250129780484712C50",
        ] {
            assert_eq!(syndrome(&hex(m)), 0, "{m}");
        }
    }

    /// Any single bit flipped anywhere in a message changes the syndrome. A
    /// polynomial implemented with the wrong bit order can still give zero on
    /// good frames while failing to notice errors, which is the silent failure
    /// this rules out.
    #[test]
    fn every_single_bit_error_is_caught() {
        let good = hex("8D40621D58C382D690C8AC2863A7");
        for byte in 0..good.len() {
            for bit in 0..8 {
                let mut bad = good.clone();
                bad[byte] ^= 1 << bit;
                assert_ne!(syndrome(&bad), 0, "byte {byte} bit {bit} went unnoticed");
            }
        }
    }

    /// Sealing a message with an address overlaid gives that address back as
    /// the syndrome — the property the whole surveillance-reply path rests on.
    #[test]
    fn an_overlaid_address_comes_back_as_the_syndrome() {
        let mut m = hex("20001910000000");
        crate::crc::seal(&mut m, 0x48_4148);
        assert_eq!(syndrome(&m), 0x48_4148);
        let mut m = hex("8D40621D58C382D690C8AC000000");
        crate::crc::seal(&mut m, 0);
        assert_eq!(syndrome(&m), 0);
        assert_eq!(&m[11..], &hex("2863A7")[..], "and a sealed squitter matches the real one");
    }
}
